site_name: Aurora CLI
repo_name: Aurora CLI GitHub
site_dir: docs-static
site_url: https://keygenqt.github.io/aurora-cli/
repo_url: https://github.com/keygenqt/aurora-cli
site_description: Makes life easier for developers on Aurora OS.

# Navigation
nav:
  - Main: index.md
  - Features:
      - Overview: cli/main.md
      - Methods:
          - Device:
              - Package:
                  - Install: cli/device/package/install.md
                  - Remove: cli/device/package/remove.md
                  - Run: cli/device/package/run.md
              - Command: cli/device/command.md
              - SSH copy: cli/device/ssh-copy-id.md
              - Upload: cli/device/upload.md
          - Emulator:
              - Package:
                  - Install: cli/emulator/package/install.md
                  - Remove: cli/emulator/package/remove.md
                  - Run: cli/emulator/package/run.md
              - Command: cli/emulator/command.md
              - Recording: cli/emulator/recording.md
              - Screenshot: cli/emulator/screenshot.md
              - Start: cli/emulator/start.md
              - Upload: cli/emulator/upload.md
          - Flutter:
              - Project:
                  - Format: cli/flutter/project/format.md
                  - Icons: cli/flutter/project/icons.md
                  - Report: cli/flutter/project/report.md
              - Available: cli/flutter/available.md
              - Custom Devices: cli/flutter/custom-device.md
              - Install: cli/flutter/install.md
              - Installed: cli/flutter/installed.md
              - Remove: cli/flutter/remove.md
          - Platform SDK:
              - Package:
                  - Install: cli/psdk/package/install.md
                  - Remove: cli/psdk/package/remove.md
                  - Search: cli/psdk/package/search.md
                  - Sign: cli/psdk/package/sign.md
                  - Validate: cli/psdk/package/validate.md
              - Project:
                  - Format: cli/psdk/project/format.md
                  - Icons: cli/psdk/project/icons.md
              - Sudoers:
                  - Add: cli/psdk/sudoers/add.md
                  - Remove: cli/psdk/sudoers/remove.md
              - Available: cli/psdk/available.md
              - Clear: cli/psdk/clear.md
              - Install: cli/psdk/install.md
              - Installed: cli/psdk/installed.md
              - Remove: cli/psdk/remove.md
              - Targets: cli/psdk/targets.md
          - Aurora SDK:
              - Available: cli/sdk/available.md
              - Install: cli/sdk/install.md
              - Installed: cli/sdk/installed.md
              - Tool: cli/sdk/tool.md
          - VS Code:
              - Tuning: cli/vscode/tuning.md
          - Settings:
              - List: cli/settings/list.md
              - Clear: cli/settings/clear.md
              - Hint: cli/settings/hint.md
              - Select: cli/settings/select.md
              - Verbose: cli/settings/verbose.md
              - Localization: cli/settings/localization.md
          - API: cli/api.md
  - Configuration:
      - Configuration: config.md
      - Settings: settings.md
  - Install:
      - Install: install.md
# Assets
extra_css:
  - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0
  - assets/css/index.css
  - assets/css/error.css
  - assets/css/common.css

# Extensions
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Configuration
theme:
  name: 'material'
  language: 'en'
  custom_dir: docs/assets
  favicon: images/favicon.ico
  template: index.html
  icon:
    logo: custom/icon
  features:
    - toc.integrate
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
